### ISSUE TITLE
V1 Checklist

### ISSUE THREAD

**Issue by bencbernstein** [bencbernstein/Simple-Synth#15]
- [x] Sun, Moon, Clouds Vector Design - Ben
- [x] Sun, Moon, Clouds Core Graphics Implement - Ben
- [x]  Palette Enum Scaffolding - Oliver
- [x] Palette Color Implementation - Ben
- [x] Toplight Flower and Honeycomb - Oliver or Ben
- [x]  Bug - Circle appears on waveform - Oliver
- [x] Tweak Sounds - Ben
- [x] Tapping animal changes delay. button on lower right opens 3 animal choices - Oliver
- [x] nature or master animal for icon - Oliver
- [x] Animation colors for waveform - Oliver or Ben, last

// 1.1 ...
- [x] Mist 
... Loads weather depending on user location
